algoritmo "CalculaIdade"
var
   ano, nasc , idade: inteiro
inicio
      escreva( " Em que amo estamos? ")
      leia(ano)
      escreva("Em que ano vc nasceu ? ")
      leia(nasc)
      idade <- ano - nasc
      escreva ("Em " , ano, " voce tera", idade , " anos.")
      se (idade >=  21 ) entao
         escreval(" E ja tera atingido a maioridade. ")
      Senao

      
      fimse
fimalgoritmo